### PR TITLE
Unit test coverage #1

### PR DESCRIPTION
**Pull request by michalkonturek**
**NB** Please merge this before PR #9 

This pull request:
- adds `.gitignore` file
- integrates `CocoaPods` to the source project
- adds `OCMocks` for the UnitTest target only
- pod files are committed to the project (yes, this is for a reason, very good reason)
- adds unit test coverage for `SWHttpTrafficRecorder`
- ~~splits `SWRecordingProtocol` from `SWHttpTrafficRecorder`~~ (requested by @JinlianWang )
- replaces source project reference from `RecorderDemo` with source directory reference
- updates `.travis.yml` to reflect changes

Roadmap, once this pull request is merged:
- ~~provide unit test coverage for `SWRecordingProtocol`~~
- provide integration tests for entire suite

### CODE REVIEW

**Comment by JinlianWang** [comment]
@michalkonturek It is great to see some test cases added; though just a heads-up, I need more time to dig into the changes to SWHttpTrafficRecorder.h and SWHttpTrafficRecorder.m to make sure the change there is sound (not changing something significant just for testing purpose, or if we have to, any other alternative; we also do not want to make sure it is back compatible).  By the way, the reason we keep protocol inside the recorder is intentional (easier to copy two files than 4), is there a reason to separate it out now?

**Comment by michalkonturek** [comment]
@JinlianWang thank you for your time dealing the this pull request.

Please know I was very cautious about changing source code which could affect it's functionality. The only changes I did to the source code were code formatting and class extraction (`SWRecordingProtocol`).

The reason to separate `SWRecordingProtocol` is not only for unit and integration testing, but also for functionality extension purposes. The library should allow users to pass their own protocols and reporters, which is something I am thinking to implement in the phase 3.

When it comes to backwards compatibility, it does not matter if the `SWRecordingProtocol` is a private or public class as users only operate on the `SWHttpTrafficRecorder` instance.

The library is most likely to be installed via `CocoaPods` or `Carthage`, and as for manual installation, in my opinion copying 2 or 4 files does not really matter that much as you usually copy a source folder. 

Let me know your thoughts.

**Comment by JinlianWang** [comment]
@michalkonturek Still would prefer to keep the source code change minimum when developing testing suites, unless necessary. Thanks!

**Comment by michalkonturek** [comment]
@JinlianWang Sure, as you requested, I will move `SWRecordingProtocol` back inside `SWHttpTrafficRecorder`.

**Comment by michalkonturek** [comment]
@JinlianWang Please know I moved `SWRecordingProtocol` back inside `SWHttpTrafficRecorder` class as you requested.

**Comment by michalkonturek** [comment]
How's it going?

**Comment by JinlianWang** [comment]
@michalkonturek Generally not strong at unit testing. Could you educate me over your comment about exposing some extra interfaces - "the interface below had to be temporarily exposed until the next phase"? What is your plan for next phase? Is it a general practice to expose some more interfaces just for testing purpose? How can be balance the code cleanness vs the need of testing?

**Comment by michalkonturek** [comment]
@JinlianWang there was supposed to be a next phase of testing, but you requested changes to be made (several comments above), so there will be no next phase. 

I do not think I can be more gentle about this, but in software engineering, there is an axiom that a testable code is a clean code and untested code, is not a clean code. 

So, my question is, are you planning to merge this PR? If not, please close this PR.

**Comment by JinlianWang** [comment]
I agree with the comment that the code shall be tested,  though a bit hesitant and not sure over writing code in some specific way or exposing unnecessary properties in order for it to be tested. Ideally, some test suite like the way AFNetworking does it would be more preferable: https://github.com/AFNetworking/AFNetworking/tree/master/Tests/Tests. Close as requested.

**Pull request closed without merging**
